version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    network_mode: "host"
    volumes:
      - ./simulator:/app/simulator
    environment:
      # Use host network to directly access the native Ollama service
      - OLLAMA_BASE_URL=http://localhost:11434
      # Define the LLM to use here!
      - OLLAMA_MODEL=gpu-agent:latest
    depends_on:
      - simulator

  simulator:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["python", "-m", "simulator.generate_telemetry"]
    volumes:
      - ./simulator:/app/simulator

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
